// Versión de la app y changelog en lenguaje de usuario (se muestra en "Novedades").
// APP_VERSION se deriva SIEMPRE de la primera entrada del changelog: agregá la entrada
// nueva arriba de todo y la versión se actualiza sola (ver docs/RELEASE.md).
export const CHANGELOG: { version: string; fecha: string; cambios: string[] }[] = [
  {
    version: "2.15.0",
    fecha: "2026-08-14",
    cambios: [
      "Al reportar un problema por Consultas ahora podés adjuntar una captura: sacala y pegala con Ctrl+V, sin tener que guardarla como archivo primero. La ve quien administra el sistema y vos; el resto del equipo no.",
      "El trabajo que adelantás de un mes que todavía no llegó ya no desaparece cuando ese mes arranca.",
    ],
  },
  {
    version: "2.14.0",
    fecha: "2026-08-14",
    cambios: [
      "Los fines de semana y los feriados dejaron de contar como demora. Una tarea entregada el viernes y revisada el lunes figuraba con cuatro días de espera; dos de esos días la oficina estaba cerrada. El jefe ahora carga los feriados desde Administración.",
      "El arqueo y cualquier tarea de todos los días se ven en UNA sola tarjeta con el avance del mes (\"6 de 21 días hábiles\") y los días adentro, en vez de una tarjeta por día.",
      "Las columnas del tablero se pliegan. Plegada muestra el título y cuántas tareas tiene, y si arrastrás algo encima se abre sola.",
      "Nuevo registro de transferencias de clientes dentro de la tarea que las controla, con aviso cuando una se parece a otra ya cargada. El aviso no bloquea: muestra la parecida y pregunta si es la misma.",
      "El aviso de \"¿seguís con esto?\" y el de riesgo del resumen ahora cuentan días de trabajo. Antes una tarea tocada el viernes a la tarde disparaba el aviso el miércoles.",
      "\"Cumplimiento del mes\" ahora mira el mes. Antes sumaba tareas terminadas de meses anteriores, así que subía solo con el paso del tiempo y no bajaba de 90% aunque no se hiciera nada. Es probable que veas el número más bajo, y es el correcto.",
      "Una pestaña dejada abierta cuando cambia el mes ya no muestra el tablero vacío. Antes parecía que se había perdido todo, y lo que se marcaba después quedaba guardado en el mes viejo.",
      "El semáforo del Cierre detecta de verdad cuando las tareas que se repiten no arrancaron el mes en cero. Daba luz verde justo en el caso que había que detectar.",
      "Mirando el día de otra persona, la pantalla dice \"Su día\" y no \"Mi día\".",
      "Cuando una función todavía no está habilitada, la app lo dice en castellano y te dice a quién avisarle, en vez de nombrar un número de migración. Y ya no dice \"no disponible\" mientras está cargando.",
    ],
  },
  {
    version: "2.13.1",
    fecha: "2026-08-05",
    cambios: [
      "El aviso de \"Base de datos al día\" de Administración volvió a decir la verdad: venía revisando sólo hasta la migración 28 y daba el visto bueno sin mirar las nueve siguientes, entre ellas la que cierra un permiso de seguridad. Ahora las revisa todas.",
    ],
  },
  {
    version: "2.13.0",
    fecha: "2026-08-05",
    cambios: [
      "La app abre más rápido: se sacó una librería de animación que pesaba casi lo mismo que media aplicación y se usaba en una sola pantalla.",
    ],
  },
  {
    version: "2.12.0",
    fecha: "2026-08-04",
    cambios: [
      "El historial de una tarea ahora muestra lo que pasó en el mes que estás mirando, en vez de todo mezclado desde que se creó. Los otros meses siguen a un click.",
      "Al crear una tarea ahora elegís si es de una sola vez o si se repite todos los meses. Por defecto es de una sola vez, así lo puntual no vuelve para siempre.",
      "Nuevo para jefes y encargados: \"En qué anda el equipo\", con lo que cada persona tiene abierto y desde cuándo. Sirve para repartir la carga y dar una mano, no para medir a nadie.",
      "El jefe puede configurar qué pesa más al sugerir por dónde empezar: vencimiento, prioridad, tareas que esperan por ésta, o lo rápido de sacar. La app explica siempre por qué una tarea va primero.",
    ],
  },
  {
    version: "2.11.0",
    fecha: "2026-08-04",
    cambios: [
      "Si el reinicio mensual no corrió, el tablero ahora lo avisa en vez de dejarte viendo el estado del mes pasado sin explicación.",
      "El jefe puede reiniciar el mes desde ese mismo aviso, con un botón que dice antes qué va a pasar y después cuántas tareas archivó y reinició.",
    ],
  },
  {
    version: "2.10.0",
    fecha: "2026-07-30",
    cambios: [
      "El jefe ya puede blanquear la contraseña de alguien desde Administración, sin depender de nadie. Se muestra una vez, se anota y se le pasa a la persona.",
      "Si te blanquean la contraseña, te llega un aviso dentro de la app diciendo quién lo hizo.",
      "Cuando falla el ingreso, ahora dice qué pasó y qué hacer, en vez de \"Usuario no encontrado\". Distingue usuario inexistente, contraseña equivocada, falta de conexión y demasiados intentos seguidos.",
      "Corregido: un encargado no podía guardar la recurrencia de una tarea de su equipo ni ver lo que registraban en las operativas.",
    ],
  },
  {
    version: "2.9.0",
    fecha: "2026-07-30",
    cambios: [
      "Si publicamos una versión nueva mientras tenés la app abierta, ahora te avisa y te ofrece actualizar con un botón. Antes mostraba un error genérico con un \"Reintentar\" que en ese caso no podía funcionar.",
      "Las pantallas de error ahora dicen qué pasó en lenguaje claro, ofrecen la acción que de verdad sirve según el caso, y te dejan copiar el detalle para mandarlo por Consultas.",
      "Si algo falla en segundo plano, ahora te enterás con un aviso en vez de que la acción quede sin efecto en silencio.",
      "Corregido: las tarjetas del tablero y del reporte no mostraban su sombra. Un error en el estilo hacía que el navegador la descartara por completo.",
      "Mientras carga una pantalla ahora se ve la forma de lo que viene, en lugar de la palabra \"Cargando\".",
      "Tipografía unificada en toda la app: se acabaron las diferencias de medio píxel entre pantallas.",
      "Al navegar con el teclado ahora se ve claramente dónde estás parado, también dentro del menú lateral oscuro.",
      "Si tenés activado \"reducir movimiento\" en tu sistema, la app lo respeta.",
      "Una tarea con datos incompletos ya no puede tumbar una pantalla entera: se muestra lo que se puede y se avisa del resto.",
    ],
  },
  {
    version: "2.8.0",
    fecha: "2026-07-27",
    cambios: [
      "Períodos: ahora podés adelantar trabajo del mes que viene y queda guardado aparte, sin pisar el mes en curso. Elegí el mes en el selector del tablero y cargá tus tareas de agosto desde julio.",
      "Cada mes guarda su propio estado, checklist y avance de forma independiente: cerrar un mes no borra lo que adelantaste en el siguiente.",
      "El mes en curso sigue funcionando exactamente igual que siempre; los cambios aplican a los meses adelantados.",
      "Al entrar, ahora se abre directamente tu tablero. Antes aparecía una pantalla que podía verse vacía hasta que apretabas \"Mi tablero\".",
      "Las consultas, sugerencias y errores que reporta el equipo ahora llegan a una cuenta de administración del sistema, aparte y reservada. El jefe ya no las ve: si alguien reporta un problema, va a quien lo puede resolver.",
      "Cada columna del tablero tiene ahora su propio menú para ordenar y agrupar, independiente de las otras. Por ejemplo: \"Pendiente\" por vencimiento y agrupada por categoría, y \"Terminado\" sin agrupar. Se guarda por tablero.",
      "Imprimir el Reporte en PDF ya no sale en blanco: ahora se abre una vista limpia, pensada para papel, con los indicadores y las tablas del período.",
      "Nuevo: Director. El estado del área en una sola pantalla — riesgos, dependencias, calendario, continuidad y planificación, cada uno con su semáforo. Para jefes y encargados.",
      "Reporte: nuevo \"Flujo de trabajo en el mes\". Muestra día por día cuándo se concentra el trabajo de cada persona, para poder repartir mejor la carga.",
      "Reporte: se distingue el trabajo que estaba previsto del que entró como urgencia. Cuando las urgencias mandan, el problema es de planificación, no de quien la ejecuta.",
      "Director: \"Qué conviene hacer\" propone acciones concretas a partir de lo que pasa en el equipo — y si el registro no es confiable, en vez de arriesgar conclusiones sugiere corregirlo primero.",
      "Director: \"Si nadie hace nada\" muestra qué vence mañana, en 3 y en 7 días, con las categorías principales.",
      "Director: \"Confianza del dato\" indica qué tan representativo es lo registrado. Un valor bajo invalida las métricas de ese conjunto, no a la persona.",
      "En \"Mi día\", si una tarea tuya lleva varios días sin moverse, aparece un aviso discreto para confirmar si seguís con ella, marcarla terminada o posponerlo. Solo lo ves vos.",
      "Cerrar un mes ahora lo deja de solo lectura, con candado en el selector. Se puede consultar pero no editar; para modificarlo, se reabre desde Cierre.",
      "Organigrama: junto a la evolución de cada persona se indica si sus resultados son parejos o dispares entre meses.",
      "Director: el panel \"Confianza del dato\" trae un sello que traduce el puntaje a algo que se lee de un vistazo, para saber si conviene fiarse de las métricas del período.",
      "En \"Mi día\" aparece una línea con la última tarea que venías trabajando, para retomar sin buscarla. Si no hay nada claro que retomar, no se muestra.",
      "Desde \"Mi día\" podés marcar una tarea como terminada con un solo toque, sin abrirla, y deshacerlo desde el mismo aviso. Los arqueos siguen pidiendo que elijas el resultado.",
      "Las tareas recurrentes diarias ahora guardan el checklist y las observaciones de cada día por separado: lo que tildaste ayer ya no se pierde.",
      "Nuevo en \"Mi día\": los viernes a la tarde aparece \"Tu semana\", con la lista de lo que terminaste y cuántas cerraste en fecha. Es privado, solo lo ves vos, y si la semana no tuvo cierres directamente no aparece.",
      "Corregido: la app podía quedar en blanco al terminar de cargar, en la versión de períodos.",
    ],
  },
  {
    version: "2.7.0",
    fecha: "2026-07-22",
    cambios: [
      "Organigrama corregido: ahora se ve una sola estructura y la máxima autoridad aparece siempre, mires la marca que mires.",
      "El buscador (Ctrl+K) encuentra a todas las personas de tu equipo, sin importar el rol.",
      "Resumen: ahora podés filtrar por marca y sucursal, igual que en el reporte.",
      "Etiquetas en las tareas: poné varias (por ejemplo la empresa) además de la categoría, y filtrá o buscá por ellas.",
      "Empresas: cargá CUIT, cierre de balance y si reporta a fábrica, para priorizar el trabajo automáticamente.",
      "Reporte: análisis de tareas operativas por persona y por tipo, para detectar qué consume más tiempo del esperado.",
      "El tablón muestra solo los vencimientos de IVA y Libro IVA Digital, sin la información que no usábamos.",
    ],
  },
  {
    version: "2.6.0",
    fecha: "2026-07-22",
    cambios: [
      "Calendario fiscal: generá de una vez los vencimientos del mes (IVA, F931, IIBB, SICORE) con vista previa antes de confirmar.",
      "Tareas operativas con meta: cargá cuántas van y mirá la barra de progreso.",
      "Al pedir licencia podés dejar novedades para quien te cubre, y ver qué tareas quedan con vencimiento en ese período.",
      "Reporte: comparativa de marcas y sucursales mes a mes.",
      "Organigrama: cómo viene evolucionando cada persona, para acompañar a quien necesite apoyo.",
      "Resumen: seguimiento de lo que delegaste y qué lleva días sin moverse.",
      "Cierre: si al ritmo actual el mes no llega a cerrarse, te avisa con tiempo.",
      "Reporte: detecta categorías que hace una sola persona, para formar un reemplazo antes de que haga falta.",
      "El buscador (Ctrl+K) ahora busca en todas tus tareas, no solo en las que tenés a la vista.",
      "Mover tarjetas y marcar notificaciones como leídas ahora responde al instante.",
    ],
  },
  {
    version: "2.5.0",
    fecha: "2026-07-22",
    cambios: [
      "Mis arqueos: mirá tu historial de diferencias de caja del mes, con el detalle de qué faltó y qué sobró.",
      "Al registrar una diferencia ahora elegís si falta o sobra plata, así el número queda bien cargado.",
      "Cierre del día: un repaso al final de tu jornada para no dejarte nada abierto.",
      "Si un vencimiento tuyo es hoy o mañana, te llega un aviso.",
      "Reporte: nuevo indicador de retrabajo, para detectar tareas que se reabren seguido.",
      "Reporte: cómo evolucionan las diferencias de caja mes a mes.",
      "Resumen: radar de vencimientos, que avisa cuáles podrían no llegar a tiempo.",
      "La campana de notificaciones ahora se actualiza al instante.",
      "La app carga más rápido: pesa un 20% menos al abrirla.",
    ],
  },
  {
    version: "2.4.0",
    fecha: "2026-07-21",
    cambios: [
      "Consultas: desde el menú de tu perfil podés mandar consultas, sugerencias o avisar errores, y ver la respuesta.",
      "Cerrá tu mes cuando vos terminaste: podés tener junio y julio abiertos a la vez, sin que uno trabe al otro.",
      "Tiempo máximo por tarea: se puede configurar cuántas horas debería llevar cada tipo de tarea, y queda registrado si se pasa.",
      "Ahora se ve quién está en línea y cuándo fue su última conexión.",
      "Nuevo campo Dato de control a adjuntar para anotar una referencia, código o comprobante en la tarea.",
      "El tablero agrupado ahora usa carriles: la tarea cambia de columna sin salirse de su grupo.",
    ],
  },
  {
    version: "2.3.0",
    fecha: "2026-07-20",
    cambios: [
      "Cierre del mes unificado: una sola pantalla te muestra con un semáforo si el mes quedó cerrado (checklist, historial guardado y tareas recurrentes en cero).",
      "El análisis mensual del reporte ahora se exporta a Excel con un click.",
      "Adjuntos en las tareas: subí comprobantes y archivos directamente en cada tarea (PDF, imágenes, Excel).",
      "Aviso de sin conexión: si se corta internet, la app te lo dice antes de que pierdas cambios.",
      "Administración muestra si la base de datos está al día o falta aplicar alguna actualización.",
      "Resumen semanal automático en el tablón con lo importante de la semana (se activa con una configuración).",
    ],
  },
  {
    version: "2.2.0",
    fecha: "2026-07-20",
    cambios: [
      "Categorías: ahora cualquier persona puede asignarlas y filtrar por ellas en su tablero, no solo jefes y encargados.",
      "Mi día: tu agenda del día con lo urgente primero.",
      "Arqueo de caja con resultado (ok o con diferencias) directamente desde tu día.",
      "Avisos en el tablón con prioridad, vencimiento y ahora se pueden eliminar definitivamente.",
      "Sucursales: organizá y filtrá el tablero y el reporte por marca y sucursal.",
      "Nuevo modo de agrupación del tablero: elegí cómo querés ver tus tareas, con varias opciones a elección.",
      "Registro de vacaciones y cobertura de tareas mientras alguien está de licencia.",
      "Buscador rápido de avisos con Ctrl+K.",
      "Plantillas para crear tareas frecuentes en un solo paso.",
      "Alertas para gestores cuando algo necesita atención antes de que sea un problema.",
      "Menciones con @ en los comentarios de las tareas, con notificación para la persona mencionada.",
      "Reporte con métricas de uso del tiempo del equipo.",
      "Reporte: análisis ejecutivo del mes con cumplimiento por persona, marca y sucursal, más tu rendimiento promedio histórico para ver si mejoramos.",
      "Se arregló la impresión del reporte: ahora sale completa y prolija.",
      "El resumen y el reporte ahora se adaptan al rol y la jerarquía de cada persona.",
      "Reporte: el indicador de puntualidad ahora muestra cuántas tareas se midieron y avisa cuando la muestra es chica.",
      "Reporte: el análisis mensual ahora se puede exportar a Excel.",
    ],
  },
  {
    version: "2.1.0",
    fecha: "2026-07-16",
    cambios: [
      "Ahora podés editar los ítems del checklist y las tareas operativas.",
      "Delegá tareas a otra persona directamente desde el tablero.",
      "El calendario está disponible para todo el equipo, no solo para jefes.",
      "Nuevo organigrama para ver la estructura del equipo.",
      "Anotaciones privadas: notas que solo ves vos.",
      "Cierre mensual con checklist de fin de mes.",
      "Tareas recurrentes con seguimiento de cumplimiento diario.",
      "Los avisos de vencimiento ahora se ven de forma más clara.",
      "Modo oscuro más limpio, con mejor separación entre tarjetas.",
      "La barra lateral queda fija: ya no se cierra sola al navegar.",
      "Podés iniciar sesión con tu nombre de usuario.",
    ],
  },
  {
    version: "2.0.0",
    fecha: "2026-07-13",
    cambios: ["Migración completa a la nueva plataforma."],
  },
];

export const APP_VERSION = CHANGELOG[0].version;
